### ISSUE TITLE
Cannot get preview image of Amazon URL

### ISSUE THREAD

**Issue by briansanteliz** [AndrejGajdos/link-preview-generator#17]
Hello, i have trying get images preview of url products. I used this package in my project and works with Ebay, Mercadolibre, Newegg but with Amazon not get image. Example of image preview Amazon:

![image-example-amazon](https://images-na.ssl-images-amazon.com/images/G/01/gno/sprites/nav-sprite-global-1x-hm-dsk-reorg._CB405937547_.pngl)

I would like you to help me, since most of the product urls come from this website. Thanks!

**Comment by AndrejGajdos** [comment]
@Brian-Santeliz I took a look at it and unfortunately, this is out of the scope of this library.

This library uses Puppeteer headless browser. [Function](https://github.com/AndrejGajdos/link-preview-generator/blob/master/index.js#L17) for getting url image is looking for images in meta tags and then in html body.

If you open amazon product url in your web browser, there is no `og:image` meta tag. However, if you open it in Puppeteer there is `og:image` which is not accessible.

<img width="1312" alt="Screenshot 2021-03-28 at 19 25 28" src="https://user-images.githubusercontent.com/1593758/112766992-9c3e3400-9014-11eb-8c81-8cb0bcabd2e4.png">

I cannot update this library just because Amazon implemented some anti-scraping logic. You would need to create your own fork and update function for getting images based on your needs.

**Comment by briansanteliz** [comment]
Hello @AndrejGajdos, understand the problem, thanks for the suggestion, the way I solved it as you mention is by using a custom function to get the featured image of the product. Unfortunately there are pages that do not have this type of tag: `og:image` for this case is best create a custom function. Thanks!

**Comment by AndrejGajdos** [comment]
@Brian-Santeliz that's great, always happy to provide some guidance.
