### ISSUE TITLE
Not Working for this website

### ISSUE THREAD

**Issue by a3igner** [AndrejGajdos/link-preview-generator#5]
I am sorry but it is not working for 

 "https://www.bloomberg.com/news/articles/2020-06-20/europe-will-have-a-digital-tax-no-matter-what-says-breton?srnd=premium-europe"

Possible to fix it?

**Comment by AndrejGajdos** [comment]
@a3igner I would need more details. Do you get an error message?

**Comment by a3igner** [comment]
Yes!

It says “are you a robot?”

**Comment by AndrejGajdos** [comment]
Yes, you are getting this error, because Bloomberg doesn't want you to allow your server to scrape their website.

This plugin uses [puppeteer-extra-plugin-stealth](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) to avoid detection, but many websites invest a lot into blocking web scraping their websites. You need to make [some dev ops optimization](https://www.scraperapi.com/blog/5-tips-for-web-scraping) to avoid blocking. If it helps you, let me know please what works for you to avoid Bloomberg's detection.
